is_gpu: true
gpu: 0
iid: false
num_users: 20
epochs: 40
local_ep: 5
frac: 1
local_bs: 16
optimizer: "adam"
lr: !!float 1e-4
momentum: 0.9
weight_decay: !!float 1e-4
download: false
verbose: false
management: true
print_every: 100
input_shape: [3,32,32]
mid_server: [5]