is_gpu: true
gpu: 0
iid: true
num_users: 10
model: "cnn"
num_classes: 10
epochs: 10
local_ep: 5
frac: 0.1
local_bs: 256
optimizer: "sgd"
lr: 0.01
momentum: 0.9
weight_decay: 1e-4
download: false
verbose: false
management: true
print_every: 100

mid_server: [2]