base: default.yaml

strategy: "Splitfedavg"
dataset: "ham10000"
metadata_path: "data/HAM10000/HAM10000_metadata.csv"
image_dirs: [
    "data/HAM10000/HAM10000_images_part_1",
    "data/HAM10000/HAM10000_images_part_2",
]

model: "resnet50"
num_classes: 7