dataset: cifar10
model: cnn
input_channels: 3
output_channels: 10
batch_size: 128
num_clients: 1  # For centralized training
lr: 0.01
num_communication: 100  # This will be our number of epochs
momentum: 0.9
seed: 1
cuda: true
dataset_root: ./data 