base: default.yaml

strategy: "fednova"
dataset: "ham10000"
metadata_path: "data/HAM10000/HAM10000_metadata.csv"
image_dirs: [
    "data/HAM10000/HAM10000_images_part_1",
    "data/HAM10000/HAM10000_images_part_2",
]
model: "vgg"
num_classes: 7
local_bs: 4