is_gpu: true
gpu: 0
iid: true
num_users: 50
epochs: 60
local_ep: 5
frac: 0.1
local_bs: 16
optimizer: "adam"
lr: !!float 1e-4
momentum: 0.9
weight_decay: !!float 1e-4
verbose: false
management: true
print_every: 1

mid_server: [5]
