base: default.yaml

strategy: "hier_fedavg"
dataset: "ham10000"
metadata_path: "data/HAM10000/HAM10000_metadata.csv"
image_dirs: [
    "data/HAM10000/HAM10000_images_part_1",
    "data/HAM10000/HAM10000_images_part_2",
]
t1: 10
t2: 20

model: "vgg"
num_classes: 7