is_gpu: true
gpu: 0
iid: true
num_users: 200
epochs: 200
frac: 0.1
local_bs: 128
optimizer: "sgd"
lr: !!float 1e-3
momentum: 0.9
weight_decay: !!float 1e-4
download: false
verbose: false
management: true
print_every: 100

mid_server: [10]
