base: default.yaml

strategy: "hier_fedavg"
dataset: "ham10000"
metadata_path: "/mnt/Data/HAM10000/HAM10000_metadata.csv"
image_dirs: [
    "/mnt/Data/HAM10000/HAM10000_images_part_1",
    "/mnt/Data/HAM10000/HAM10000_images_part_2",
]
t1: 10
t2: 20

model: "resnet50"
num_classes: 10