base: default.yaml

strategy: "H-SFP"
dataset: "isic-2018"
train_image_data_folder_path: "data/ISIC2018/ISIC2018_Task1-2_Training_Input"
train_mask_data_folder_path: "data/ISIC2018/ISIC2018_Task1_Training_GroundTruth"
test_image_data_folder_path: "data/ISIC2018/ISIC2018_Task1-2_Validation_Input"
test_mask_data_folder_path: "data/ISIC2018/ISIC2018_Task1_Validation_GroundTruth"

model: "resnet50"
num_classes: 2
t1: 10
t2: 20
