is_gpu: true
gpu: 0
iid: true
num_users: 200
epochs: 200
frac: 0.1
local_bs: 16
optimizer: "adam"
lr: !!float 1e-4
momentum: 0.9
weight_decay: !!float 1e-4
verbose: false
print_every: 1

input_size: 32
mid_server: [5]

ssl_epochs_client: 10
ssl_epochs_edge: 10
syn_epochs_cloud: 10
syn_samples_per_class: 50
