is_gpu: true
gpu: 0
iid: true
num_users: 20
epochs: 200
frac: 0.5
local_bs: 16
optimizer: "adam"
lr: !!float 1e-4
momentum: 0.9
weight_decay: !!float 1e-4
download: false
verbose: false
management: true
print_every: 100

input_size: 32
mid_server: [5]
