base: default.yaml

strategy: "hier_fedavg"
dataset: "ham10000"
metadata_path: "/mnt/Data/HAM10000/HAM10000_metadata.csv"
image_dirs:
  [
    "/mnt/Data/HAM10000/HAM10000_images_part_1",
    "/mnt/Data/HAM10000/HAM10000_images_part_2",
  ]
t1: 25
t2: 50

model: "vgg"
num_classes: 7
local_bs: 4
input_size: 224
