is_gpu: true
gpu: 0
iid: true
num_users: 10
model: "cnn"
num_classes: 10
epochs: 100
local_ep: 5
frac: 0.1
local_bs: 256
optimizer: "sgd"
lr: 0.01
momentum: 0.9
weight_decay: 1e-4
verbose: false
print_every: 100