experiment:
  baseline: "fedavg"
  dataset: "CIFAR100"              # MNIST | CIFAR10 | FashionMNIST
  model: "CIFAR100_CNN"                  # MLP | CNN | ResNet
  rounds: 50
  clients: 20
  tiers: 3
  scenario: "non-iid"           # iid | non-iid
  noniid_type: "dirichlet"      # dirichlet | label-split
  alpha: 1.0
  classes_per_client: 3

training:
  local_epochs: 1
  batch_size: 32
  lr: 0.01
  optimizer: "SGD"              # SGD | Adam | RMSprop
  loss: "CrossEntropy"          # CrossEntropy | MSE