_wandb:
    value:
        cli_version: 0.26.1
        e:
            g75jo2vc2zgwz1eq9dbufcq9bo9t74gc:
                args:
                    - --task
                    - classification
                    - --method
                    - h-sfp
                    - --cfg
                    - configs/classification/h-sfp/cifar_our_alexnet_10_20.yaml
                    - --wandb
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "502392610816"
                        used: "446574731264"
                email: dung27062002@gmail.com
                executable: /home/jackson/miniconda3/envs/AAAI-2026/bin/python
                git:
                    commit: 108ea14260f3e35d75d389edf336dfe0e2a72989
                    remote: https://github.com/Jackson2706/Split-Federated-Merging-Learning.git
                gpu: NVIDIA GeForce RTX 3080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3080 Ti
                      uuid: GPU-6dda3136-2646-ba6a-c16d-c8ca6664841f
                host: jackson
                memory:
                    total: "32518979584"
                os: Linux-6.11.0-29-generic-x86_64-with-glibc2.40
                program: /home/jackson/Desktop/Split-Federated-Merging-Learning/main.py
                python: CPython 3.9.23
                root: /home/jackson/Desktop/Split-Federated-Merging-Learning
                startedAt: "2026-05-13T15:49:58.919529Z"
                writerId: g75jo2vc2zgwz1eq9dbufcq9bo9t74gc
        m: []
        python_version: 3.9.23
        t:
            "2":
                - 1
                - 5
                - 41
                - 53
                - 79
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.9.23
            "5": 0.26.1
            "10":
                - 20
            "12": 0.26.1
            "13": linux-x86_64
base:
    value: default.yaml
cfg:
    value: configs/classification/h-sfp/cifar_our_alexnet_10_20.yaml
dataset:
    value: cifar10
dataset_root:
    value: /mnt/Data/cifar/
method:
    value: h-sfp
model:
    value: alexnet
num_classes:
    value: 10
strategy:
    value: HSFL
t1:
    value: 10
t2:
    value: 20
task:
    value: classification
