experiment:
  baseline: "hfedprotogencl"
  dataset: "CIFAR100"
  model: "CIFAR100_CNN"
  rounds: 50
  edges: 3
  clients: 20
  tiers: 3
  scenario: "non-iid"
  noniid_type: "dirichlet"
  alpha: 1.0
  classes_per_client: 3

training:
  local_epochs: 1
  batch_size: 32
  lr: 0.01
  optimizer: "SGD"
  loss: "CrossEntropy"
