base: default.yaml

strategy: "hier_fedavg"
dataset: "cifar"
dataset_root: "/mnt/Data/cifar/"
t1: 25
t2: 50

# Prefer F1 score
epsilon: 3.0
delta: !!float 1e-6
clip_norm: 1.0
clip: false

# Balanced
# epsilon: 1.5
# delta: !!float 1e-5
# clip_norm: 2.0
# clip: true