base: default.yaml

strategy: "HeteroSFL"
dataset: "isic-2018"
train_image_data_folder_path: "data/ISIC2018/ISIC2018_Task1-2_Training_Input"
train_mask_data_folder_path: "data/ISIC2018/ISIC2018_Task1_Training_GroundTruth"
test_image_data_folder_path: "data/ISIC2018/ISIC2018_Task1-2_Validation_Input"
test_mask_data_folder_path: "data/ISIC2018/ISIC2018_Task1_Validation_GroundTruth"

model: "resnet50"
num_classes: 2
server_in_channels: 512
wide_channels: 76
narrow_channels: 4
high_end_ratio: 0.3
